 
# Konfigurasi Build untuk Netlify
[build]
  # Perintah untuk build proyek Anda
  command = "npm run build"

  # Direktori output setelah build selesai
  publish = "dist"

# Aturan Redirect untuk Single Page Application (SPA)
# Ini adalah bagian yang akan memperbaiki error "Page Not Found"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
